# Generated by Django 3.0.6 on 2020-05-13 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('contraseña', models.CharField(max_length=20)),
                ('imagen', models.FileField(null=True, upload_to='perfil/')),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('precio', models.FloatField(default=0)),
                ('negociable', models.BooleanField()),
                ('descripcion', models.CharField(max_length=350)),
                ('on_line', models.CharField(max_length=2)),
                ('fecha_modificacion', models.DateTimeField(verbose_name='fecha_modificacion')),
                ('ip', models.CharField(max_length=100)),
                ('foto', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.Categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.Usuario')),
            ],
        ),
    ]
