# Generated by Django 3.0.6 on 2020-05-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.FileField(null=True, upload_to='anuncios/static/perfiles'),
        ),
    ]
