# Generated by Django 3.0.6 on 2020-05-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_auto_20200513_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_validado',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
