# Generated by Django 3.0.6 on 2020-05-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_auto_20200514_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.FileField(null=True, upload_to='static/perfiles'),
        ),
    ]
