# Generated by Django 3.0.6 on 2020-05-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_auto_20200518_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email_validado',
            field=models.BooleanField(default=0),
        ),
    ]
