# Generated by Django 3.0.6 on 2020-05-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0006_auto_20200518_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.FileField(null=True, upload_to='static/perfiles'),
        ),
    ]
